paths:
  /api/products:
    get:
      summary: Obtenemos todos los productos de la base datos
      tags: 
        - Products
      responses: 
        "200":
          description: Se obtiene todos los usuarios correctamente
          content: 
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/User"                
        "500":
          description: Error interno del servidor
    post:
      summary: este endpoint crea un nuevo usuario
      tags:
        - Users
      requestBody:
        required: true
        content: 
          application/json:
            schema:
              $ref: "#components/requestBodies/createUser"
      responses:
        "201":
          description: Usuario creado correctamente
        "500":
          description: Error interno del servidor
     
  /api/users/{uid}:
    get:
      summary: Obtiene un solo usuario por ID
      tags: 
        - Users
      parameters:
      - name: uid
        in: path
        required: true
        description: Id del usuario que se quire solicitar
        schema:
          $type: String
      responses: 
        "200":
          description: Usuario encontrado
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#components/schemas/User"
        "500":
          description: Error interno del servidor     
components: 
  schemas: 
    User:
      type: object
      properties:
        _id:
          type: ObjectId
          description: ID autogenerado por MongoDb
        first_name: 
          type: string
          description: Nombre del usuario
        last_name: 
          type: string
          description: Apellido del usuario
        password:
          type: string
          description: Password del usuario
      example:
        _id: ObjectId("12345")
        first_name: Tinki
        last_name: Winki
        password: 1234
  requestBodies: 
    createUser:
      type: object
      properties:
        first_name: 
          type: string
          description: Nombre del usuario
        last_name: 
          type: string
          description: Apellido del usuario
        password:
          type: string
          description: Password del usuario
        email: 
          type: string
          description: Email del usuario
      example: 
        first_name: Firu
        last_name: Lais
        password: 1234
        email: firu@lais.com



        